//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Linq.UI.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Concepts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Concepts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Practica.Linq.UI.App_GlobalResources.Concepts", typeof(Concepts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver objeto customer.
        /// </summary>
        internal static string Consigna1 {
            get {
                return ResourceManager.GetString("Consigna1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver lista de productos ordenados por unit in stock de mayor a menor..
        /// </summary>
        internal static string Consigna10 {
            get {
                return ResourceManager.GetString("Consigna10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver las distintas categorías asociadas a los productos.
        /// </summary>
        internal static string Consigna11 {
            get {
                return ResourceManager.GetString("Consigna11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver el primer elemento de una lista de productos.
        /// </summary>
        internal static string Consigna12 {
            get {
                return ResourceManager.GetString("Consigna12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver los customer con la cantidad de ordenes asociadas.
        /// </summary>
        internal static string Consigna13 {
            get {
                return ResourceManager.GetString("Consigna13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver todos los productos sin stock.
        /// </summary>
        internal static string Consigna2 {
            get {
                return ResourceManager.GetString("Consigna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver todos los productos que tienen stock y que cuestan más de 3 por
        ///unidad.
        /// </summary>
        internal static string Consigna3 {
            get {
                return ResourceManager.GetString("Consigna3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver todos los customers de la Región WA.
        /// </summary>
        internal static string Consigna4 {
            get {
                return ResourceManager.GetString("Consigna4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver el primer elemento o nulo de una lista de productos donde el ID de
        ///producto sea igual a 789.
        /// </summary>
        internal static string Consigna5 {
            get {
                return ResourceManager.GetString("Consigna5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver los nombre de los Customers. Mostrarlos en Mayuscula y en
        ///Minuscula..
        /// </summary>
        internal static string Consigna6 {
            get {
                return ResourceManager.GetString("Consigna6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver Join entre Customers y Orders donde los customers sean de la 
        ///Región WA y la fecha de orden sea mayor a 1/1/1997..
        /// </summary>
        internal static string Consigna7 {
            get {
                return ResourceManager.GetString("Consigna7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver los primeros 3 Customers de la  Región WA.
        /// </summary>
        internal static string Consigna8 {
            get {
                return ResourceManager.GetString("Consigna8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query para devolver lista de productos ordenados por nombre.
        /// </summary>
        internal static string Consigna9 {
            get {
                return ResourceManager.GetString("Consigna9", resourceCulture);
            }
        }
    }
}
